apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: monitoring

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.bachelor.wcrw.de`)
      kind: Rule
      services:
        - name: prometheus-stack-grafana
          port: 80
  tls:
     certResolver: myresolver
