apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://helm.traefik.io/traefik"  
    chart: traefik
    targetRevision: 10.20.0
    helm:
      values: | 
        additionalArguments:
          - --certificatesresolvers.myresolver.acme.tlschallenge
          - --certificatesresolvers.myresolver.acme.email=wolfma99@gmail.com
          - --certificatesresolvers.myresolver.acme.storage=/cert/acmeproductive.json
          - --certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
        ports:
          web:
            redirectTo: websecure
        ingressRoute:
          dashboard:
            enabled: false
        persistence:
          enabled: false
          path: /cert
          size: 128Mi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
