apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-ego
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/WolfMa99/vault-ego-helm-chart.git"  
    targetRevision: "main"
    path: templates
  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
